### ISSUE TITLE
dYdX V4 orders aren't received by dydx.trade

### ISSUE THREAD

**Issue by adrianmess** [junta/tradingview-alert-connector#24]
Hi, 
I've been using your **dydx-tradingview-integration** github repo to make trades on dydx V3. I created a new webservice and used **tradingview-alert-connector** to trade on dydx V4 and but the trades aren't making it to the dydx4 exchange. I'm not seeing any error messages in my webservice logs. I've provided what I see in my logs below. Not sure what i'm missing. I'm hoping you can provide some guidance. 

**TradingView Alert Message:** 
{
"exchange": "dydxv4",
"strategy":"SOL_USD",
"market":"SOL_USD",
"size":"10",
"reverse":false,
"order":"{{strategy.order.action}}",
"position":"{{strategy.market_position}}",
"price":"{{strategy.order.price}}"
}

**Webservice Log**
Recieved Tradingview strategy alert: {
  exchange: 'dydxv4',
  strategy: 'SOL_USD',
  market: 'SOL_USD',
  size: '10',
  reverse: false,
  order: 'buy',
  position: 'long',
  price: '115.931'
}
strategyData { reverse: false, isFirstOrder: 'true' }
latestPrice 115.931
orderParams for dydx { market: 'SOL-USD', side: 'BUY', size: 10, price: 115.931 }

**Comment by junta** [comment]
Hi,
I've made some changes yesterday, 
so, could you please check if your deployed version is the latest one?
https://tv-connector.gitbook.io/docs/setup/faq#how-to-deploy-the-latest-version-of-the-tool

also, did you export your mnemonic phrase on dydx website?
https://tv-connector.gitbook.io/docs/setup/dydx-v4-setup#export-your-secret-phrase-a-set-of-24-words-from-dxdx-website-then-put-it-in-.env-file

**Comment by adrianmess** [comment]
Hi, 
I can confirm I deployed the latest version. I did export my mnemonic phrase to an .env file, here is an example of what my .env file looks like, it's a fake phrase for demonstration purposes. 

# Required variables for dydx4
DYDX_V4_MNEMONIC=orange papaya fig kiwi cherry mango banana raspberry honeydew xigua grape zucchini elderberry cherry date papaya vanilla banana xigua raspberry fig orange tangerine honeydew

**Comment by adrianmess** [comment]
Hi,
I just deployed the latest commit and i'm getting an error now when an alert is received. I have provided it below. I also I did export my mnemonic phrase to an .env file

TypeError: Cannot read properties of undefined (reading 'address')
    at get address [as address] (/app/node_modules/@dydxprotocol/v4-client-js/build/src/clients/subaccount.js:13:37)
    at CompositeClient.placeOrderMessage (/app/node_modules/@dydxprotocol/v4-client-js/build/src/clients/composite-client.js:283:83)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
